name: Commit Check Action
description: Check commit message formatting, branch naming, committer name, email, and more
author: shenxianpeng
branding:
  icon: "git-commit"
  color: "blue"
inputs:
  message:
    description: check commit message formatting convention
    required: false
    default: true
  branch:
    description: check git branch naming convention
    required: false
    default: true
  author-name:
    description: check committer author name
    required: false
    default: true
  author-email:
    description: check committer author email
    required: false
    default: true
  commit-signoff:
    description: check committer commit signature
    required: false
    default: true
  dry-run:
    description: run checks without failing
    required: false
    default: false
  job-summary:
    description: add a job summary
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Install action dependencies
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          # https://github.com/pypa/setuptools/issues/3269
          export DEB_PYTHON_INSTALL_LAYOUT=deb
        fi
        python3 -m pip install -r "$GITHUB_ACTION_PATH/requirements.txt"
    - name: Run commit-check
      shell: bash
      run: python3 ${{ github.action_path }}/main.py
      env:
        MESSAGE: ${{ inputs.message }}
        BRANCH: ${{ inputs.branch }}
        AUTHOR_NAME: ${{ inputs.author-name }}
        AUTHOR_EMAIL: ${{ inputs.author-email }}
        COMMIT_SIGNOFF: ${{ inputs.commit-signoff }}
        DRY_RUN: ${{ inputs.dry-run }}
        JOB_SUMMARY: ${{ inputs.job-summary }}
