name: Commit Check Action
description: Check commit message formatting, branch naming, committer name, email, and more
author: shenxianpeng
branding:
  icon: "git-commit"
  color: "blue"
inputs:
  message:
    description: check git commit message following conventional commits
    required: false
    default: true
  branch:
    description: check git branch name following conventional branch
    required: false
    default: true
  author-name:
    description: check committer author name
    required: false
    default: false
  author-email:
    description: check committer author email
    required: false
    default: false
  dry-run:
    description: run checks without failing
    required: false
    default: false
  job-summary:
    description: display job summary to the workflow run
    required: false
    default: true
  pr-comments:
    description: post results to the pull request comments
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Install dependencies and run commit-check
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          # https://github.com/pypa/setuptools/issues/3269
          export DEB_PYTHON_INSTALL_LAYOUT=deb
        fi

        # Set up virtual environment
        python3 -m venv venv
        source venv/bin/activate

        # Download artifact
        python3 -m pip download -r "$GITHUB_ACTION_PATH/requirements.txt"

        # Verify artifact attestations
        if ! gh attestation verify commit_check-*.whl -R commit-check/commit-check; then
            echo "Artifact verification failed. Aborting installation."
            exit 1
        fi

        # Install artifact
        python3 -m pip install commit_check-*.whl pygithub-*.whl

        python3 "$GITHUB_ACTION_PATH/main.py"
      env:
        MESSAGE: ${{ inputs.message }}
        BRANCH: ${{ inputs.branch }}
        AUTHOR_NAME: ${{ inputs.author-name }}
        AUTHOR_EMAIL: ${{ inputs.author-email }}
        DRY_RUN: ${{ inputs.dry-run }}
        JOB_SUMMARY: ${{ inputs.job-summary }}
        PR_COMMENTS: ${{ inputs.pr-comments }}
