name: Commit Check Action
description: Check commit message formatting, branch naming, committer name, email, and more
author: shenxianpeng
branding:
  icon: "git-commit"
  color: "blue"
inputs:
  message:
    description: check commit message formatting convention
    required: false
    default: true
  branch:
    description: check git branch naming convention
    required: false
    default: true
  author-name:
    description: check committer author name
    required: false
    default: true
  author-email:
    description: check committer author email
    required: false
    default: true
  dry-run:
    description: run checks without failing
    required: false
    default: false
  summary:
    description: add a job summary
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
        BRANCH: ${{ inputs.branch }}
        AUTHOR_NAME: ${{ inputs.author-name }}
        AUTHOR_EMAIL: ${{ inputs.author-email }}
        DRY_RUN: ${{ inputs.dry-run }}
        SUMMARY: ${{ inputs.summary }}
