name: Release Drafter
permissions:
  contents: read

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  draft-release:
    uses: commit-check/.github/.github/workflows/release-drafter.yml@main
